// Golden trace snapshots — the CHARACTERIZATION baseline for current combat
// behavior. One committed `.trace.txt` file per scenario under
// ./__snapshots__/, generated by formatTrace over a real simulateCombat run
// with { trace: true }. These are NOT hand-edited; they are blessed via
// `vitest -u` (or first-run auto-write) and re-verified on every subsequent
// run via toMatchFileSnapshot. A diff here means combat behavior changed —
// review it, don't silently re-bless.
//
// PURE inputs (SCENARIOS + gameData), no behavior change: this file only
// calls simulateCombat with the trace option already added by the engine.

import { describe, it, expect } from "vitest";
import { simulateCombat } from "../src/engine.js";
import { gameData } from "@autobattler/data";
import { SCENARIOS } from "./fixtures/scenarios.js";
import { formatTrace } from "./fixtures/formatTrace.js";

describe("combat trace golden snapshots", () => {
  for (const scenario of SCENARIOS) {
    it(`${scenario.name}: trace matches the committed golden snapshot`, async () => {
      const result = simulateCombat(scenario.boardA, scenario.boardB, scenario.seed, gameData, {
        trace: true,
      });
      const rendered = formatTrace(scenario, result);
      await expect(rendered).toMatchFileSnapshot(`./__snapshots__/${scenario.name}.trace.txt`);
    });

    it(`${scenario.name}: a second independent run renders an identical trace`, async () => {
      const result = simulateCombat(scenario.boardA, scenario.boardB, scenario.seed, gameData, {
        trace: true,
      });
      const rendered = formatTrace(scenario, result);
      await expect(rendered).toMatchFileSnapshot(`./__snapshots__/${scenario.name}.trace.txt`);
    });
  }
});
